name: RSpec Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.118.0
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Install FractalNow
        run: |
          sudo apt-get update && sudo apt-get install fractalnow -yy

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run RSpec tests
        run: bundle exec rspec
